### PR TITLE
Add examples of using null-terminated strings.

### PR DESCRIPTION
**Pull request by dtarditi**
Here are some examples of using null-terminated strings adapted from K&R.   The code illustrates some basic aspects of using strings, as well as the sometimes trickier aspects of writing to a string.

I plan to clean up the code once the compiler change for making count(0) be the default bounds for nt_array_ptr is complete.

### CODE REVIEW

**Comment by mwhicks1** [comment]
These examples compile for me and are helpful. Thanks!

One question: I see that you included the following headers for this example:
```
#include <ctype.h>
#include <stdchecked.h>
#include <stdio_checked.h>
```
Does this mean that the checked versions of stdio.h, stdlib.h etc. are not automatically chosen by the compiler? Should I be changing references to, say, `stdio.h` in code that I'm porting to be `stdio_checked.h` ?

**Comment by mwhicks1** [comment]
One thing I am confused about, of the examples:
```
checked int my_strlen(nt_array_ptr<char> p : count(0)) {
  int i = 0;
  nt_array_ptr<char> s : count(i) = p; /* 1 */
  while (s[i] != '\0')
    ++i; /* 2 */
  return i;
}
```
I don't understand why this works. Statement `/* 1 */` implies that `s` has bounds `s` to `s+i`. Does statement `/* 2 */` effectively expand the bounds on `s`, which is justified by the NUL check that precedes it?

**Comment by mwhicks1** [comment]
One more question, this time about the last example. The type of `main` is as follows:
```
int main(int argc, nt_array_ptr<char> argv[] : count(argc)) {
```
Here, the `count` refers to `argv`, not the strings it contains. But you write `argv` with type `[]` and not as an `array_ptr` --- why is this OK? I checked that the following works, so I am wondering about the difference.
```
int main(int argc, array_ptr<nt_array_ptr<char>> argv : count(argc)) {
```

**Comment by dtarditi** [comment]
To answer Mike's questions:
1. Yes, you should change references to headers to use the checked versions of them when available.  The compiler is not automatically choosing them.
2. Yes, statement 2 widens the bounds at the ++i.   This is justified by the preceding null check.
3. Good catch - the [] should be checked[].   Otherwise we end up with a bounds-safe interface.   Note that if the body of main is in  a checked scope, this doesn't matter.  Anything with a bounds-safe interface is treated as thought it were checked.

In some cases, I modified the original code K&R code to change `char []` to `nt_array_ptr<char>`.   I could have changed it to use zt_checked[] instead.

**Pull request merged**
